### ISSUE TITLE
cannot running as demo

### ISSUE THREAD

**Issue by Dragonwarri0r** [lzane/Fingers-Detection-using-OpenCV-and-Python#7] opened 2018-05-29 11:58 UTC
when i press b to get background and n to start,it can running a little time but gradually my hand integrate into backgroud(black).

**Comment by struggling-man** [comment] 2018-06-02 14:17
I have the same situation. can you help me!

**Comment by lzane** [comment] 2018-06-02 14:33
Have you try to set different parameters? This CV approach is easy light-affected.
It's a very old project so I nearly forget the detail.

Anyway, I will try it on my computer when I can reach one.

Good Luck~

**Comment by lzane** [comment] 2018-06-02 14:53
Hey, I have noticed that the issue was caused by the new version of OpenCV api's modification.

Please checkout https://docs.opencv.org/3.4/d7/d7b/classcv_1_1BackgroundSubtractorMOG2.html#a682adde901148d85450435e6cc0de4a1

I wrote my code with OpenCV2, sorry for not testing the other contributor's pull request. 

I will push a new version of code in a few minutes.

**Comment by lzane** [comment] 2018-06-02 14:56
@Dragonwarri0r @struggling-man Plz pull the new version.

Hope it works for you guys. :)

**Comment by taojinglong** [comment] 2019-07-09 07:32
When we use the latest version of opencv,line 96 in the new.py should be changed to this

- ~~_, contours, hierarchy = cv2.findContours(thresh1, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)~~


- contours, hierarchy = cv2.findContours(thresh1, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)

**Comment by lzane** [comment] 2019-07-10 06:22
@taojinglong you are right.

As the document show, that's because of the breaking change of the `findContours` api.

Since the project I write is in OpenCV 3, I Don't have plan to change it from the source code. 

But I will find time to add the notice to the README

Doc:
- [OpenCV 4](https://docs.opencv.org/4.0.0/d3/dc0/group__imgproc__shape.html#gae4156f04053c44f886e387cff0ef6e08)
- [OpenCV 3](https://docs.opencv.org/3.4.6/d3/dc0/group__imgproc__shape.html#ga17ed9f5d79ae97bd4c7cf18403e1689a)

**Comment by lzane** [comment] 2019-08-26 14:08
Close this issue since it's solved.

**Closed as completed by lzane** 2019-08-26 14:08 UTC

**Comment by vedant10** [comment] 2019-12-07 06:45
How to display the number of fingers in number. Eg 1 or 2 or 10
